import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile); const TIMEOUT_MS=20000;
function rootDir(env){const root=String(env.OPERATOR_WORKSPACE_ROOT||'').trim();if(!root) throw new Error('workspace_root_not_configured');return path.resolve(root);}
function assertSafePath(root,target){const resolved=path.resolve(target);if(resolved!==root&&!resolved.startsWith(root+path.sep))throw new Error('workspace_path_outside_allowlist');return resolved;}
async function git(root,args){return exec('git',args,{cwd:root,timeout:TIMEOUT_MS,maxBuffer:2000000});}
async function hashFile(file){const data=await fs.readFile(file);return crypto.createHash('sha256').update(data).digest('hex');}
async function manifest(root){const out=[];async function walk(dir,rel=''){const entries=await fs.readdir(dir,{withFileTypes:true});for(const e of entries.sort((a,b)=>a.name.localeCompare(b.name))){if(['.git','.operator-checkpoints','node_modules','.next','dist','build','coverage'].includes(e.name))continue;const rp=rel?path.join(rel,e.name):e.name;const full=path.join(dir,e.name);if(e.isDirectory())await walk(full,rp);else if(e.isFile()){const st=await fs.stat(full);out.push({path:rp.replaceAll(path.sep,'/'),size:st.size,sha256:await hashFile(full)});}}}await walk(root);return out;}
export async function runWorkspace(input,env=process.env){const root=rootDir(env);const action=String(input.action||'health');const task=input.task||{};if(action!=='health'&&!(task.allowedActions||[]).includes('workspace_read'))throw new Error('workspace_read_not_authorized');await fs.access(root);const executionId='workspace-'+(task.taskId||Date.now());if(action==='health'){let gitOk=false;try{await git(root,['rev-parse','--show-toplevel']);gitOk=true;}catch{}return {executionId,target:root,result:{status:200,action,gitOk}};}if(action==='snapshot'){const [status,head,files]=await Promise.all([git(root,['status','--short']).then(x=>x.stdout).catch(()=>''),git(root,['rev-parse','HEAD']).then(x=>x.stdout.trim()).catch(()=>null),manifest(root)]);const payload={version:1,executionId,root,head,status:status.split('\n').filter(Boolean),files,timestamp:new Date().toISOString()};const checkpointRoot=assertSafePath(root,path.join(root,'.operator-checkpoints'));await fs.mkdir(checkpointRoot,{recursive:true});const id=crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex').slice(0,16);await fs.writeFile(path.join(checkpointRoot,id+'.json'),JSON.stringify({...payload,checkpointId:id},null,2)+'\n','utf8');return {executionId,target:root,result:{status:200,action,checkpointId:id,head,files:files.length}};}if(action==='diff'){const diff=await git(root,['diff','--no-ext-diff','--unified=3']).then(x=>x.stdout);const status=await git(root,['status','--short']).then(x=>x.stdout);return {executionId,target:root,result:{status:200,action,diff:diff.slice(0,1000000),statusText:status}};}throw new Error('workspace_action_not_supported');}
export function verifyWorkspaceResult({result,action}){const passed=Boolean(result&&result.result&&result.result.status>=200&&result.result.status<300&&result.executionId);return {verifierId:'workspace-independent-verifier-v1',passed,errors:passed?[]:['workspace_'+(action||'unknown')+'_verification_failed']};}