import http from 'node:http';
import process from 'node:process';

const port=Number(process.env.GATEWAY_PORT||8789);
const platform=String(process.env.EASY_PLATFORM_URL||'http://127.0.0.1:8790').replace(/\/$/,'');
const operator=String(process.env.EASY_OPERATOR_URL||'http://127.0.0.1:8792').replace(/\/$/,'');
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EASY Platform</title><style>body{margin:0;font-family:system-ui;background:#050b14;color:#eaf2ff;min-height:100vh;display:grid;place-items:center}.card{max-width:760px;margin:24px;padding:36px;border:1px solid #28415b;border-radius:22px;background:#0a1422;box-shadow:0 20px 70px #0008}h1{font-size:clamp(36px,8vw,72px);margin:0 0 12px}p{color:#9eb1c7;line-height:1.6}.status{display:inline-block;padding:8px 12px;border-radius:999px;border:1px solid #28415b;margin:10px 0 20px}.btn{display:inline-block;padding:13px 18px;border-radius:10px;background:#68d5ff;color:#06111a;text-decoration:none;font-weight:800}.small{font-size:12px}</style></head><body><main class="card"><div class="status" id="status">Checking platform…</div><h1>EASY</h1><p>Developer Platform control plane: projects, agent work, builds, Guardian, verification, APIs, tools and the guarded AI Operator.</p><a class="btn" id="enter" href="${platform}/">Enter EASY Platform</a><p class="small">The gateway refuses to claim readiness until the platform health endpoint responds.</p></main><script>fetch('/api/gateway/status').then(r=>r.json()).then(x=>{document.getElementById('status').textContent=x.platformOnline&&x.operatorOnline?'● Platform + Operator verified':x.platformOnline?'● Platform verified · Operator unverified':'● Platform unverified';document.getElementById('status').style.color=x.platformOnline&&x.operatorOnline?'#59e391':'#ffd166'}).catch(()=>document.getElementById('status').textContent='● Platform unverified')</script></body></html>`;
const send=(res,status,data,type='application/json; charset=utf-8')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)};
async function health(url,path){try{const r=await fetch(url+path);return r.ok}catch{return false}}
async function proxy(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);const target=operator+u.pathname+u.search;let raw='';for await(const c of req){raw+=c;if(raw.length>100_000)return send(res,413,{error:'body_too_large'})}const headers={};if(req.headers['content-type'])headers['content-type']=req.headers['content-type'];if(req.headers.authorization)headers.authorization=req.headers.authorization;try{const r=await fetch(target,{method:req.method,headers,body:['GET','HEAD'].includes(req.method)?undefined:raw});const text=await r.text();res.writeHead(r.status,{'content-type':r.headers.get('content-type')||'application/json; charset=utf-8','cache-control':'no-store'});res.end(text)}catch{return send(res,502,{error:'operator_unavailable'})}}

http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/api/gateway/status')return send(res,200,{service:'easy-platform-gateway',platformOnline:await health(platform,'/api/health'),operatorOnline:await health(operator,'/api/operator/health'),platform,operator});if(u.pathname.startsWith('/api/operator/'))return proxy(req,res);if(req.method==='GET'&&u.pathname==='/')return send(res,200,page,'text/html; charset=utf-8');return send(res,404,{error:'not_found'})}).listen(port,()=>console.log(`EASY gateway listening on ${port}`));
