import http from 'node:http';
import crypto from 'node:crypto';
import { resolve } from 'node:path';
import { mkdir } from 'node:fs/promises';
import { submit, runOnce } from './operator-worker.mjs';
import { loadState } from './operator-state.mjs';
import { intelligenceStatus } from './operator-intelligence.mjs';
import { executeGithubChange } from './github-operator-executor.mjs';
import { providerReadiness } from './provider-readiness.mjs';

const port=Number(process.env.EASY_OPERATOR_PORT||8792);
const bind=process.env.EASY_OPERATOR_BIND||'127.0.0.1';
const stateFile=resolve(process.env.EASY_OPERATOR_STATE||'.easy/operator-state.json');
const workspaceRoot=resolve(process.env.EASY_OPERATOR_WORKSPACE||'.');
const apiKey=process.env.EASY_OPERATOR_API_KEY||'';
const oidcAudience=String(process.env.EASY_GITHUB_OIDC_AUDIENCE||'https://easy-platform-runtime-v3-production.up.railway.app');
const oidcRepository=String(process.env.EASY_GITHUB_OIDC_REPOSITORY||'salamou1944/Easy-');
const oidcWorkflow=String(process.env.EASY_GITHUB_OIDC_WORKFLOW||'salamou1944/Easy-/.github/workflows/army-14-practical-easy-gate.yml@refs/heads/main');
let oidcJwksCache={expiresAt:0,keys:[]};

const send=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data));};
const authorized=req=>{if(!apiKey)return true;const presented=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const a=Buffer.from(presented),b=Buffer.from(apiKey);return a.length===b.length&&crypto.timingSafeEqual(a,b)};
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100_000)throw Object.assign(new Error('body_too_large'),{status:413})}if(!raw)return{};try{return JSON.parse(raw)}catch{throw Object.assign(new Error('invalid_json'),{status:400})}}
function projectWorkspace(project){if(typeof project!=='string'||!project.trim())return workspaceRoot;const target=resolve(workspaceRoot,project);const prefix=workspaceRoot.endsWith('/')?workspaceRoot:workspaceRoot+'/';if(target!==workspaceRoot&&!target.startsWith(prefix))return null;return target}
function decodePart(value){return JSON.parse(Buffer.from(value,'base64url').toString('utf8'))}
async function githubJwks(){if(Date.now()<oidcJwksCache.expiresAt&&oidcJwksCache.keys.length)return oidcJwksCache.keys;const r=await fetch('https://token.actions.githubusercontent.com/.well-known/jwks');if(!r.ok)throw new Error('oidc_jwks_unavailable');const data=await r.json();if(!Array.isArray(data.keys)||!data.keys.length)throw new Error('oidc_jwks_empty');oidcJwksCache={keys:data.keys,expiresAt:Date.now()+10*60*1000};return data.keys}
async function verifyGitHubOidc(token){const parts=String(token||'').split('.');if(parts.length!==3)throw new Error('oidc_token_invalid');let header,payload;try{header=decodePart(parts[0]);payload=decodePart(parts[1])}catch{throw new Error('oidc_token_invalid')}if(header.alg!=='RS256'||!header.kid)throw new Error('oidc_token_algorithm_invalid');const keys=await githubJwks();const jwk=keys.find(k=>k.kid===header.kid&&k.kty==='RSA');if(!jwk)throw new Error('oidc_signing_key_unknown');const key=crypto.createPublicKey({key:jwk,format:'jwk'});const signature=Buffer.from(parts[2],'base64url');const valid=crypto.verify('RSA-SHA256',Buffer.from(`${parts[0]}.${parts[1]}`),key,signature);if(!valid)throw new Error('oidc_signature_invalid');const now=Math.floor(Date.now()/1000);if(payload.iss!=='https://token.actions.githubusercontent.com')throw new Error('oidc_issuer_invalid');if(payload.aud!==oidcAudience)throw new Error('oidc_audience_invalid');if(payload.repository!==oidcRepository)throw new Error('oidc_repository_invalid');if(payload.ref!=='refs/heads/main')throw new Error('oidc_ref_invalid');if(payload.workflow_ref!==oidcWorkflow)throw new Error('oidc_workflow_invalid');if(!Number.isFinite(payload.exp)||payload.exp<=now)throw new Error('oidc_expired');if(Number.isFinite(payload.nbf)&&payload.nbf>now+30)throw new Error('oidc_not_yet_valid');return payload}
function extractResponseText(data){if(typeof data?.output_text==='string'&&data.output_text.trim())return data.output_text;for(const item of data?.output||[]){for(const content of item?.content||[]){if(typeof content?.text==='string'&&content.text.trim())return content.text}}throw new Error('provider_empty')}
async function requestOpenAIPlan(prompt){const token=process.env.EASY_OPENAI_API_KEY||process.env.OPENAI_API_KEY||'';if(!token)throw new Error('openai_key_missing');const endpoint=process.env.EASY_OPERATOR_LLM_ENDPOINT||'https://api.openai.com/v1/responses';const model=process.env.EASY_OPERATOR_LLM_MODEL||'gpt-4.1-mini';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);try{const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({model,input:[{role:'system',content:[{type:'input_text',text:'You are Elite Code, a senior autonomous software engineer. Return JSON only. Make minimal, evidence-driven repository changes. Never request or expose secrets. Never modify CI workflows, credentials, deployment configuration, or authentication policy.'}]},{role:'user',content:[{type:'input_text',text:prompt}]}],max_output_tokens:12000}),signal:controller.signal});const raw=await response.text();let data;try{data=JSON.parse(raw)}catch{data={error:{message:raw.slice(0,1000)}}}if(!response.ok){const message=data?.error?.message||`provider_http_${response.status}`;throw new Error(`openai_${response.status}:${message}`)}return JSON.parse(extractResponseText(data))}catch(error){if(error?.name==='AbortError')throw new Error('openai_timeout');throw error}finally{clearTimeout(timer)}}
async function createOidcPlan(x,req){const presented=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!presented)throw Object.assign(new Error('oidc_authorization_required'),{status:401});const claims=await verifyGitHubOidc(presented);if(typeof x.goal!=='string'||!x.goal.trim())throw Object.assign(new Error('goal_required'),{status:400});const context=typeof x.context==='string'?x.context.slice(0,300000):'';const prompt=`Generate a verified autonomous coding plan for the EASY repository. Goal: ${x.goal.slice(0,4000)}\n\nRepository context:\n${context}\n\nReturn JSON only with exactly this shape: {"summary":"...","changes":[{"path":"relative/path.ext","content":"complete file content"}]}. Keep changes minimal and evidence-driven. Allowed paths are source/test/docs files only; never modify CI workflows, secrets, credentials, deployment configuration, authentication policy, or .env files. If no safe change is justified, return an empty changes array. The plan will be syntax-checked and applied by a separate fail-closed executor. Authenticated claims: repository=${claims.repository}; workflow_ref=${claims.workflow_ref}; ref=${claims.ref}`;try{const plan=await requestOpenAIPlan(prompt);if(!plan||!Array.isArray(plan.changes))throw new Error('plan_schema_invalid');return {status:'PLAN_READY',plan,claims:{repository:claims.repository,workflow_ref:claims.workflow_ref,ref:claims.ref,run_id:claims.run_id}}}catch(error){console.error(JSON.stringify({event:'oidc_plan_failed',error:error.message,model:process.env.EASY_OPERATOR_LLM_MODEL||'gpt-4.1-mini'}));throw Object.assign(new Error(error.message),{status:502})}}

export async function handle(req,res){
  const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);
  if(req.method==='GET'&&url.pathname==='/api/operator/health')return send(res,200,{ok:true,service:'easy-ai-operator',mode:'fail-closed',provider:'deterministic-core'});
  if(!authorized(req))return send(res,401,{error:'unauthorized'});
  try{
    if(req.method==='GET'&&url.pathname==='/api/operator/capabilities')return send(res,200,await providerReadiness());
    if(req.method==='GET'&&url.pathname==='/api/operator/status'){const state=await loadState(stateFile);return send(res,200,{service:'easy-ai-operator',queue:{queued:state.tasks.filter(t=>t.status==='QUEUED').length,running:state.tasks.filter(t=>t.status==='RUNNING').length,verified:state.tasks.filter(t=>t.status==='VERIFIED').length,failed:state.tasks.filter(t=>t.status==='FAILED').length,blocked:state.tasks.filter(t=>t.status==='BLOCKED').length},intelligence:intelligenceStatus(),providers:await providerReadiness()});}
    if(req.method==='GET'&&url.pathname==='/api/operator/tasks'){const state=await loadState(stateFile);return send(res,200,{tasks:(state.tasks||[]).slice(0,100)});}
    if(req.method==='POST'&&url.pathname==='/api/operator/oidc-plan'){const x=await body(req);return send(res,200,await createOidcPlan(x,req));}
    if(req.method==='POST'&&url.pathname==='/api/operator/tasks'){const x=await body(req);if(typeof x.goal!=='string'||!x.goal.trim())return send(res,400,{error:'goal_required'});const workspace=projectWorkspace(x.project);if(!workspace)return send(res,400,{error:'invalid_project'});await mkdir(workspace,{recursive:true});const task=await submit(x.goal.slice(0,4000),{project:x.project||null},{stateFile,workspace});return send(res,202,task);}
    if(req.method==='POST'&&url.pathname==='/api/operator/run-once'){const x=await body(req);const workspace=projectWorkspace(x.project);if(!workspace)return send(res,400,{error:'invalid_project'});await mkdir(workspace,{recursive:true});const result=await runOnce({stateFile,workspace,maxAttempts:1});return send(res,200,{result});}
    if(req.method==='POST'&&url.pathname==='/api/operator/github/execute'){const x=await body(req);const result=await executeGithubChange({owner:x.owner,repo:x.repo,base:x.base,title:x.title,body:x.body,changes:x.changes,approved:x.approved===true,token:process.env.GITHUB_TOKEN||process.env.EASY_GITHUB_TOKEN});return send(res,result.status==='VERIFIED'?200:result.status==='WAITING_APPROVAL'?428:403,result);}
    return send(res,404,{error:'not_found'});
  }catch(error){return send(res,error.status||500,{error:error.message||'operator_error'});}
}

if(import.meta.url===`file://${process.argv[1]}`){const server=http.createServer(handle);server.listen(port,bind,()=>console.log(JSON.stringify({service:'easy-ai-operator',bind,port,stateFile,workspaceRoot,oidcAudience,oidcRepository,oidcWorkflow})));}
