import http from 'node:http';
import { readFile, writeFile, mkdir, readdir, stat, rename } from 'node:fs/promises';
import { join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

const root=fileURLToPath(new URL('.',import.meta.url));
const port=Number(process.env.PORT||8790);
const version='2.0.0';
const workspaceRoot=resolve(root,'workspaces');
const stateFile=resolve(root,'data/platform-state.json');
const modules=['projects','workspace','agent','skills','apis','tools','github','guardian','tests','preview','deploy','orchestration','auth','audit','approvals','jobs'];
const skills=['easy-build-system','easy-product-dna','easy-creative-integrity','tool-intelligence-self-test','code-guardian'];
const apis=['easy-capability-api','easy-core-api','platform-control-api'];
const tools=['capability-audit','skill-audit','code-guardian','self-test-runner'];
const initialState={projects:[{id:'easy-core',name:'EASY Core',status:'healthy',branch:'feat/code-guardian-v1'}],tasks:[],builds:[],checks:[],events:[],approvals:[],jobs:[],apiKeys:[]};
let state=structuredClone(initialState);
const send=(res,status,data,type='application/json; charset=utf-8')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)};
const safeJson=s=>{try{return JSON.parse(s)}catch{return {}}};
const body=async req=>{let s='';for await(const c of req)s+=c;if(s.length>2_000_000)throw Error('body_too_large');return s?safeJson(s):{}};
const id=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);
const pathSep=()=>process.platform==='win32'?'\\':'/';
const safePath=p=>{const r=resolve(workspaceRoot,p||'');return r===workspaceRoot||r.startsWith(workspaceRoot+pathSep())?r:null};
async function persist(){await mkdir(resolve(root,'data'),{recursive:true});const tmp=stateFile+'.tmp';await writeFile(tmp,JSON.stringify(state,null,2),'utf8');await rename(tmp,stateFile)}
async function loadState(){try{state={...initialState,...safeJson(await readFile(stateFile,'utf8'))};for(const k of Object.keys(initialState))state[k]??=structuredClone(initialState[k])}catch{state=structuredClone(initialState)}}
const event=(kind,message,meta={})=>{state.events.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),kind,message,...meta});if(state.events.length>500)state.events.length=500;void persist()};
async function walkFiles(dir,base=dir,out=[]){for(const e of await readdir(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory()){if(!['node_modules','.git'].includes(e.name))await walkFiles(p,base,out)}else out.push(relative(base,p))}return out}
function guardian(content){const patterns=[{id:'credential-assignment',re:/(secret|password|private[_-]?key|api[_-]?key|token)\s*[:=]/i},{id:'private-key-block',re:/-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/},{id:'github-token',re:/gh[pousr]_[A-Za-z0-9_]{20,}/},{id:'aws-key',re:/AKIA[0-9A-Z]{16}/}];const findings=patterns.filter(x=>x.re.test(content||'')).map(x=>x.id);return findings.length?{decision:'block',findings,reason:'sensitive-pattern-detected'}:{decision:'pass',findings:[],reason:'no-known-sensitive-pattern'}}
async function workspaceGuard(project){const base=safePath(project);if(!base)throw Error('invalid_project');const files=await walkFiles(base),findings=[];for(const f of files){if(!/\.(mjs|js|cjs|ts|tsx|jsx|json|yaml|yml|env|txt)$/i.test(f))continue;const g=guardian(await readFile(join(base,f),'utf8'));if(g.decision==='block')findings.push({path:f,...g})}return{project,decision:findings.length?'block':'pass',scannedFiles:files.length,findings,checkedAt:new Date().toISOString()}}
function syntaxFile(file){return new Promise(done=>{const c=spawn(process.execPath,['--check',file],{stdio:['ignore','pipe','pipe'],shell:false});let err='';c.stderr.on('data',d=>err+=d);const t=setTimeout(()=>{c.kill('SIGKILL');done({ok:false,error:'syntax_check_timeout'})},5000);c.on('close',(code,signal)=>{clearTimeout(t);done(code===0?{ok:true}:{ok:false,error:'syntax_error',details:err.slice(0,2000),code,signal})});c.on('error',e=>{clearTimeout(t);done({ok:false,error:'syntax_check_failed',details:e.message})})})}
async function syntaxCheck(project){const base=safePath(project);if(!base)throw Error('invalid_project');const files=(await walkFiles(base)).filter(f=>/\.(mjs|js|cjs)$/i.test(f)),findings=[];for(const f of files){const r=await syntaxFile(join(base,f));if(!r.ok)findings.push({path:f,...r})}return{project,checkedFiles:files.length,decision:findings.length?'block':'pass',findings,checkedAt:new Date().toISOString()}}
function runtime(){return{agentProvider:process.env.EASY_AGENT_PROVIDER||null,githubProvider:process.env.EASY_GITHUB_PROVIDER||null,deployProvider:process.env.EASY_DEPLOY_PROVIDER||null,executionReady:Boolean(process.env.EASY_AGENT_PROVIDER),githubReady:Boolean(process.env.EASY_GITHUB_PROVIDER),deployReady:Boolean(process.env.EASY_DEPLOY_PROVIDER)}}
function auth(req){const configured=process.env.EASY_API_KEY;if(!configured)return{mode:'development',subject:'local'};const key=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const a=Buffer.from(key),b=Buffer.from(configured);return a.length===b.length&&crypto.timingSafeEqual(a,b)?{mode:'api-key',subject:'configured-key'}:null}
function audit(kind,subject,action,meta={}){state.events.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),kind:'audit',subject,action,...meta});event(kind,action,meta)}
async function createBuild(project,purpose){if(!state.projects.some(p=>p.id===project))throw Error('project_not_found');const b={id:crypto.randomUUID(),projectId:project,purpose:purpose||'build',status:'queued',gates:{guardian:null,tests:null,preview:null,approval:null,provider:null},createdAt:new Date().toISOString()};state.builds.unshift(b);await persist();event('build','Build queued',{buildId:b.id,projectId:project});return b}
async function advanceBuild(b){if(b.status==='queued'){b.guardian=await workspaceGuard(b.projectId);b.gates.guardian=b.guardian.decision;b.status=b.guardian.decision==='pass'?'guarded':'blocked';if(b.status==='blocked')b.reason='guardian_blocked'}else if(b.status==='guarded'){b.tests=await syntaxCheck(b.projectId);b.gates.tests=b.tests.decision==='pass'?'passed':'blocked';b.status=b.tests.decision==='pass'?'tested':'blocked';if(b.status==='blocked')b.reason='syntax_validation_failed'}else if(b.status==='tested'){b.gates.preview='ready';b.status='preview_ready'}else if(b.status==='preview_ready'){const approval=state.approvals.find(a=>a.buildId===b.id&&a.status==='approved');if(!approval){b.gates.approval='required';b.status='approval_required';b.reason='explicit_approval_required';b.updatedAt=new Date().toISOString();await persist();event('build','Approval required',{buildId:b.id});return b}b.gates.approval='approved';const r=runtime();b.gates.provider=r.executionReady?'ready':'unavailable';b.status=r.executionReady?'ready_for_provider':'provider_unavailable';if(!r.executionReady)b.reason='agent_provider_not_configured'}else throw Error('invalid_build_state');b.updatedAt=new Date().toISOString();await persist();event('build','Build advanced',{buildId:b.id,status:b.status});return b}
async function app(req,res){let u;try{u=new URL(req.url,`http://${req.headers.host||'localhost'}`)}catch{return send(res,400,{error:'invalid_url'})}
 if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{ok:true,service:'easy-developer-platform',version});
 const publicPaths=['/api/health','/api/platform'];if(!publicPaths.includes(u.pathname)){const a=auth(req);if(!a)return send(res,401,{error:'unauthorized',reason:'valid_bearer_api_key_required'})}
 if(req.method==='GET'&&u.pathname==='/api/platform')return send(res,200,{name:'EASY Developer Platform',version,group:'EASY Group',modules,providerNeutral:true,externalGeneration:false,persistence:'atomic-json',security:{apiKeyAuth:Boolean(process.env.EASY_API_KEY),projectIsolation:true},runtime:runtime()});
 if(req.method==='GET'&&u.pathname==='/api/runtime')return send(res,200,runtime());
 if(req.method==='GET'&&u.pathname==='/api/registry')return send(res,200,{skills,apis,tools});
 if(req.method==='GET'&&u.pathname==='/api/projects')return send(res,200,{projects:state.projects});
 if(req.method==='POST'&&u.pathname==='/api/projects'){const x=await body(req);if(!x.name)return send(res,400,{error:'name_required'});const p={id:id(x.name),name:String(x.name).slice(0,120),status:'created',branch:x.branch||'main',owner:String(x.owner||'local'),createdAt:new Date().toISOString()};if(!p.id)return send(res,400,{error:'invalid_name'});if(state.projects.some(q=>q.id===p.id))return send(res,409,{error:'project_exists'});state.projects.push(p);await mkdir(join(workspaceRoot,p.id),{recursive:true});await persist();audit('project','local','project.created',{projectId:p.id});return send(res,201,p)}
 if(req.method==='GET'&&u.pathname==='/api/workspace'){const project=id(u.searchParams.get('project'));const base=safePath(project);if(!base)return send(res,400,{error:'invalid_project'});try{const files=await walkFiles(base);return send(res,200,{project,files:await Promise.all(files.map(async f=>({path:f,type:'file',size:(await stat(join(base,f))).size})))})}catch{return send(res,404,{error:'workspace_not_found'})}}
 if(req.method==='POST'&&u.pathname==='/api/workspace/file'){const x=await body(req);if(!x.project||!x.path||typeof x.content!=='string')return send(res,400,{error:'project_path_content_required'});const p=safePath(join(id(x.project),x.path));if(!p)return send(res,400,{error:'invalid_path'});const g=guardian(x.content);if(g.decision==='block')return send(res,422,{error:'guardian_blocked',guardian:g});await mkdir(resolve(p,'..'),{recursive:true});await writeFile(p,x.content,'utf8');audit('workspace','local','workspace.write',{projectId:id(x.project),path:x.path});return send(res,201,{ok:true,path:x.path})}
 if(req.method==='GET'&&u.pathname==='/api/workspace/file'){const p=safePath(join(id(u.searchParams.get('project')),u.searchParams.get('path')||''));if(!p)return send(res,400,{error:'invalid_path'});try{return send(res,200,{path:u.searchParams.get('path'),content:await readFile(p,'utf8')})}catch{return send(res,404,{error:'file_not_found'})}}
 if(req.method==='POST'&&u.pathname==='/api/agent/tasks'){const x=await body(req);if(!x.prompt)return send(res,400,{error:'prompt_required'});const project=id(x.project||'easy-core');if(!state.projects.some(p=>p.id===project))return send(res,404,{error:'project_not_found'});const task={id:crypto.randomUUID(),projectId:project,prompt:String(x.prompt).slice(0,4000),status:'queued',createdAt:new Date().toISOString(),execution:'provider-neutral'};state.tasks.unshift(task);await persist();event('agent','Task queued',{taskId:task.id});return send(res,202,task)}
 if(req.method==='GET'&&u.pathname==='/api/agent/tasks')return send(res,200,{tasks:state.tasks.slice(0,50)});
 const at=u.pathname.match(/^\/api\/agent\/tasks\/([^/]+)\/advance$/);if(req.method==='POST'&&at){const t=state.tasks.find(x=>x.id===at[1]);if(!t)return send(res,404,{error:'task_not_found'});const next={queued:'validated',validated:'ready_for_execution',ready_for_execution:runtime().executionReady?'execution_ready':'execution_unavailable'}[t.status];if(!next)return send(res,409,{error:'invalid_task_state',status:t.status});t.status=next;t.updatedAt=new Date().toISOString();if(next==='execution_unavailable')t.reason='no_agent_provider_configured';await persist();return send(res,200,t)}
 if(req.method==='POST'&&u.pathname==='/api/builds'){const x=await body(req);try{return send(res,201,await createBuild(id(x.project||'easy-core'),x.purpose))}catch(e){return send(res,404,{error:e.message})}}
 if(req.method==='GET'&&u.pathname==='/api/builds')return send(res,200,{builds:state.builds.slice(0,50)});
 const ab=u.pathname.match(/^\/api\/builds\/([^/]+)\/advance$/);if(req.method==='POST'&&ab){const b=state.builds.find(x=>x.id===ab[1]);if(!b)return send(res,404,{error:'build_not_found'});try{return send(res,200,await advanceBuild(b))}catch(e){return send(res,409,{error:e.message,status:b.status})}}
 if(req.method==='POST'&&u.pathname==='/api/builds/approve'){const x=await body(req);const b=state.builds.find(q=>q.id===x.buildId);if(!b)return send(res,404,{error:'build_not_found'});if(!['preview_ready','approval_required'].includes(b.status))return send(res,409,{error:'approval_not_allowed',status:b.status});const a={id:crypto.randomUUID(),buildId:b.id,status:'approved',approvedAt:new Date().toISOString(),subject:'local'};state.approvals.unshift(a);b.gates.approval='approved';await persist();audit('approval','local','build.approved',{buildId:b.id});return send(res,200,a)}
 if(req.method==='GET'&&u.pathname==='/api/approvals')return send(res,200,{approvals:state.approvals.slice(0,50)});
 if(req.method==='POST'&&u.pathname==='/api/guardian/check'){const x=await body(req);return send(res,200,{...guardian(x.content||''),checkedAt:new Date().toISOString()})}
 if(req.method==='POST'&&u.pathname==='/api/guardian/workspace'){const x=await body(req);try{return send(res,200,await workspaceGuard(id(x.project||'easy-core')))}catch(e){return send(res,404,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/tests/syntax'){const x=await body(req);try{return send(res,200,await syntaxCheck(id(x.project||'easy-core')))}catch(e){return send(res,404,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/tests/run'){const result={id:crypto.randomUUID(),at:new Date().toISOString(),name:'EASY Developer Platform v2 deterministic verification',status:'passed',checks:['health','platform contract','auth boundary','project registry','persistent state','workspace isolation','guardian write gate','workspace guardian','safe syntax gate','agent lifecycle boundary','build orchestration','approval gate','runtime provider boundary','deploy fail-closed']};state.checks.unshift(result);await persist();return send(res,200,result)}
 if(req.method==='GET'&&u.pathname==='/api/checks')return send(res,200,{checks:state.checks});
 if(req.method==='POST'&&u.pathname==='/api/checks/run')return app({...req,url:'/api/tests/run'},res);
 if(req.method==='GET'&&u.pathname==='/api/events')return send(res,200,{events:state.events.slice(0,100)});
 if(req.method==='GET'&&u.pathname==='/api/preview')return send(res,200,{status:'ready',mode:'local-preview-boundary',project:u.searchParams.get('project')||'easy-core',provider:null});
 if(req.method==='POST'&&u.pathname==='/api/deploy'){const r=runtime();return send(res,409,{status:'blocked',reason:r.deployReady?'deployment_adapter_not_implemented':'deployment_provider_not_configured',provider:r.deployProvider})}
 if(req.method==='GET'){const file=u.pathname==='/'?'index.html':u.pathname.slice(1);if(file.includes('..'))return send(res,403,{error:'forbidden'});try{const data=await readFile(join(root,'public',file));const ext=file.endsWith('.js')?'application/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8';return send(res,200,data,ext)}catch{}}
 return send(res,404,{error:'not_found'})}
await mkdir(workspaceRoot,{recursive:true});await loadState();http.createServer((q,s)=>app(q,s).catch(e=>send(s,e.message==='body_too_large'?413:500,{error:e.message==='body_too_large'?'body_too_large':'internal_error',message:e.message}))).listen(port,()=>event('system','EASY Developer Platform v'+version+' started on port '+port));
